services:
  autobidsportal:
    build: .
    environment: &idautobidsenv
      DATALAD_SSH_IDENTITYFILE: "/ssh/id_rsa"
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:example@postgres:5432
      SQLALCHEMY_TRACK_MODIFICATIONS: "false"
      REDIS_URL: "redis://redis:6379"
      FLASK_APP: bids_form.py
      AUTOBIDS_SECRET_KEY: secret
      AUTOBIDS_LOG_LEVEL: INFO
      AUTOBIDS_CFMM2TAR_DOWNLOAD_DIR: /cfmm2tar-download
      AUTOBIDS_CFMM2TAR_STORAGE_DIR: /tar-files
      AUTOBIDS_TAR2BIDS_DOWNLOAD_DIR: /datasets
      AUTOBIDS_TAR2BIDS_TEMP_DIR: /tmp
      AUTOBIDS_HEURISTIC_REPO_PATH: /home
      AUTOBIDS_DCM4CHE_PREFIX: ""
      AUTOBIDS_TAR2BIDS_PREFIX: ""
      AUTOBIDS_HEURISTIC_DIR_PATH: /home
      AUTOBIDS_DATALAD_RIA_URL: "ria+ssh://user@ria:2222/ria-store"
      AUTOBIDS_DATALAD_RIA_TAR_ALIAS: "tar-files"
      AUTOBIDS_MAIL_ENABLED: "false"
      AUTOBIDS_DICOM_SERVER_URL: "ORTHANC@orthanc:4242"
      AUTOBIDS_DICOM_SERVER_USERNAME: "user"
      AUTOBIDS_DICOM_SERVER_PASSWORD: "password"
      AUTOBIDS_DICOM_SERVER_TLS: "true"
      AUTOBIDS_DICOM_SERVER_STUDYINSTANCEUID_WILDCARD: "false"
      AUTOBIDS_GITLAB_ACTIVE: "true"
      AUTOBIDS_GITLAB_URL: "http://127.0.0.1:8080"
      AUTOBIDS_GITLAB_TOKEN: "BFavxxb7gAodznnorhv7"
      AUTOBIDS_GITHUB_ACTIVE: "false"
      GIT_AUTHOR_NAME: "Autobids Portal"
      GIT_AUTHOR_EMAIL: "autobids@example.com"
      GIT_COMMITER_NAME: "Autobids Portal"
      GIT_COMMITER_EMAIL: "autobids@example.com"
    ports: ["5000:5000"]
    volumes: &idautobidsvolumes
      - "./compose/cfmm2tar-download:/cfmm2tar-download"
      - "./compose/tar-files:/tar-files"
      - "./compose/ria-store:/ria-store"
      - "./compose/datasets:/datasets"
      - "./compose/ssh:/ssh"
    depends_on:
      - postgres
      - redis
      - rq
  rq:
    build: .
    command: rq worker
    environment: *idautobidsenv
    volumes: *idautobidsvolumes
    depends_on:
      - postgres
      - redis
    restart: on-failure
  redis:
    image: redis:5.0.14
  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "./compose/postgres-db:/var/lib/postgresql/data"
    ports: ["5432:5432"]
  orthanc:
    image: jodogne/orthanc:1.10.1
    command: /run/secrets/
    secrets:
      - orthanc.json
    ports: ["4242:4242", "8042:8042"]
    volumes:
      - "./compose/orthanc-key.pem:/certs/orthanc.key"
      - "./compose/orthanc-crt.pem:/certs/orthanc.crt"
      - "./compose/dcm4che-crt.pem:/certs/cert.pem"
      - "./compose/orthanc-db:/var/lib/orthanc/db"
  ria:
    image: lscr.io/linuxserver/openssh-server
    hostname: ria
    environment:
      PUBLIC_KEY_FILE: "/ssh/id_rsa.pub"
      SUDO_ACCESS: "true"
      USER_NAME: user
      PUID: 1001
      PGID: 1001
      DOCKER_MODS: linuxserver/mods:openssh-server-git
    ports: ["2222:2222"]
    volumes:
      - "./compose/ria-store-ssh:/ria-store"
      - "./compose/ssh:/ssh"
  gitlab:
    image: gitlab/gitlab-ee:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        gitlab_rails['initial_root_password'] = 'gitlabpass'
    ports: ["8080:80"]
    volumes:
      - "./compose/gitlab/config:/etc/config"
      - "./compose/gitlab/logs:/var/log/gitlab"
      - "./compose/gitlab/data:/var/opt/gitlab"
secrets:
  orthanc.json:
    file: compose/orthanc.json
